### ISSUE TITLE
Leaderboard endpoint colour customization

### ISSUE THREAD

**Issue by rithik-b** [DaFluffyPotato/hitbloq#24]
Give patrons the option in the discord to change their leaderboard name colours like they can for backgrounds
This colour should then be returned in the leaderboard endpoint for each user, or null if there isnt one

**Comment by DaFluffyPotato** [comment]
delaying until #32 is resolved.

**Comment by DaFluffyPotato** [comment]
implemented on my end, but it just returns #ffffff as a default instead of null.

**Comment by DaFluffyPotato** [comment]
the extended endpoints for leaderboards (but not ladders) are necessary to get the `custom_color` field.
