### ISSUE TITLE
Make the map pool tiles on the website homepage clickable, instead of being a static image

### ISSUE THREAD

**Issue by Nytra** [DaFluffyPotato/hitbloq#28]
A little UX suggestion.

Right now, there is an image of some map pools on the website homepage which looks like this: https://imgur.com/kq4m2wo

As this is a static image, the user can't click on anything here. There are no hyperlinks.

I think it would be better if these tiles could be clicked on to take the user directly to the corresponding map pool page. 

Currently, if the user sees a map pool that they find interesting in this image, they need to search for it on a different page, which takes longer and could be a hassle.

**Comment by DaFluffyPotato** [comment]
That's a preview of the functionality of Hitbloq. It's not supposed to be an actual element.
