### ISSUE TITLE
Leaderboard banner in pool leaderboard endpoints

### ISSUE THREAD

**Issue by rithik-b** [DaFluffyPotato/hitbloq#30]
If someone has a patreon banner for their leaderboard in the pool, provide the link for it in the pool leaderboard endpoint

**Comment by DaFluffyPotato** [comment]
This was already a thing, but I added an extended version of the map leaderboard endpoints that includes the banners.

```
/api/leaderboard/<leaderboard_id>/nearby_scores_extended/<user> (GET)
/api/leaderboard/<leaderboard_id>/friends_extended (POST)
```
