### ISSUE TITLE
Website UI suggestions

### ISSUE THREAD

**Issue by LackWiz** [DaFluffyPotato/hitbloq#42]
Add a search function to the ranked maps page
![image](https://user-images.githubusercontent.com/74268852/164874299-17b99528-5518-4892-a342-ff82098258c1.png)
Better page flipping
![image](https://user-images.githubusercontent.com/74268852/164874376-6aa23fc3-262f-48c9-a819-f98a650868ff.png)
New Maps Section
![image](https://user-images.githubusercontent.com/74268852/164874452-e17e654d-6ae6-41c3-8fa9-21cd5c482ed8.png)

**Comment by DaFluffyPotato** [comment]
this is all planned. although the "new maps" concept is actually just going to be a feed of pool activity (ranks/manual stars/unranks/etc). it'll be below the leaderboard instead of on the side.

**Comment by DaFluffyPotato** [comment]
Split into #61 and #62.
